/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/auth/otp/request": {
    /** Request OTP for phone login */
    post: operations["requestOtp"];
  };
  "/v1/auth/otp/verify": {
    /** Verify OTP and issue auth token */
    post: operations["verifyOtp"];
  };
  "/v1/auth/logout": {
    /** Logout */
    post: operations["logout"];
  };
  "/v1/me": {
    /** Get current user */
    get: operations["getMe"];
  };
  "/v1/categories": {
    /** List categories */
    get: operations["listCategories"];
  };
  "/v1/products": {
    /** List products */
    get: operations["listProducts"];
  };
  "/v1/products/{id}": {
    /** Get product by id or slug */
    get: operations["getProduct"];
  };
  "/v1/cart": {
    /** Get cart */
    get: operations["getCart"];
  };
  "/v1/cart/items": {
    /** Add item to cart */
    post: operations["addCartItem"];
  };
  "/v1/cart/items/{id}": {
    /** Remove cart item */
    delete: operations["removeCartItem"];
    /** Update cart item */
    patch: operations["updateCartItem"];
  };
  "/v1/checkout": {
    /** Create checkout and compute totals */
    post: operations["checkout"];
  };
  "/v1/payments": {
    /** Initiate payment */
    post: operations["createPayment"];
  };
  "/v1/webhooks/sslcommerz": {
    /** SSLCommerz IPN callback */
    post: operations["sslcommerzWebhook"];
  };
  "/v1/webhooks/shurjopay": {
    /** ShurjoPay IPN callback */
    post: operations["shurjopayWebhook"];
  };
  "/v1/orders": {
    /** List orders for current user */
    get: operations["listOrders"];
  };
  "/v1/orders/{id}": {
    /** Get order */
    get: operations["getOrder"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: string;
      phone: string;
    };
    OtpRequest: {
      phone: string;
    };
    OtpChallenge: {
      challenge_id: string;
      expires_in: number;
    };
    OtpVerify: {
      challenge_id: string;
      code: string;
    };
    AuthSession: {
      token: string;
      user: components["schemas"]["User"];
    };
    Category: {
      id: string;
      slug: string;
      name_en: string;
      name_bn: string;
    };
    Money: {
      /** @default BDT */
      currency: string;
      amount: number;
    };
    ProductVariant: {
      id: string;
      sku: string;
      size: string;
      color: string;
      stock: number;
      price: components["schemas"]["Money"];
    };
    Product: {
      id: string;
      slug: string;
      title_en: string;
      title_bn: string;
      description_en?: string;
      description_bn?: string;
      primary_image: string;
      gallery?: string[];
      price: components["schemas"]["Money"];
      compare_at?: components["schemas"]["Money"];
      variants: components["schemas"]["ProductVariant"][];
      category_ids?: string[];
    };
    ProductList: {
      items: components["schemas"]["Product"][];
      next_cursor?: string | null;
    };
    CartItem: {
      id: string;
      product_id: string;
      variant_id: string;
      title_en: string;
      title_bn: string;
      image: string;
      qty: number;
      unit_price: components["schemas"]["Money"];
      line_total: components["schemas"]["Money"];
    };
    Cart: {
      id: string;
      items: components["schemas"]["CartItem"][];
      subtotal: components["schemas"]["Money"];
    };
    AddCartItem: {
      cart_id?: string;
      product_id: string;
      variant_id: string;
      qty: number;
    };
    UpdateCartItem: {
      qty: number;
    };
    CheckoutRequest: {
      cart_id: string;
      phone: string;
      /** @enum {string} */
      shipping_zone: "INSIDE_DHAKA" | "OUTSIDE_DHAKA";
    };
    ShippingQuote: {
      /** @enum {string} */
      zone: "INSIDE_DHAKA" | "OUTSIDE_DHAKA";
      fee: components["schemas"]["Money"];
    };
    CheckoutSummary: {
      cart_id: string;
      order_id: string;
      shipping: components["schemas"]["ShippingQuote"];
      subtotal: components["schemas"]["Money"];
      total: components["schemas"]["Money"];
    };
    PaymentRequest: {
      order_id: string;
      /** @enum {string} */
      provider: "SSLCOMMERZ" | "SHURJOPAY" | "COD";
    };
    PaymentSession: {
      payment_id: string;
      provider: string;
      status: string;
      redirect_url?: string | null;
    };
    Order: {
      id: string;
      status: string;
      phone: string;
      items: components["schemas"]["CartItem"][];
      shipping: components["schemas"]["ShippingQuote"];
      subtotal: components["schemas"]["Money"];
      total: components["schemas"]["Money"];
      /** Format: date-time */
      created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Request OTP for phone login */
  requestOtp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpRequest"];
      };
    };
    responses: {
      /** @description OTP request accepted */
      200: {
        content: {
          "application/json": components["schemas"]["OtpChallenge"];
        };
      };
    };
  };
  /** Verify OTP and issue auth token */
  verifyOtp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpVerify"];
      };
    };
    responses: {
      /** @description OTP verified */
      200: {
        content: {
          "application/json": components["schemas"]["AuthSession"];
        };
      };
    };
  };
  /** Logout */
  logout: {
    responses: {
      /** @description Logged out */
      204: {
        content: never;
      };
    };
  };
  /** Get current user */
  getMe: {
    responses: {
      /** @description Current user */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /** List categories */
  listCategories: {
    responses: {
      /** @description Category list */
      200: {
        content: {
          "application/json": components["schemas"]["Category"][];
        };
      };
    };
  };
  /** List products */
  listProducts: {
    parameters: {
      query?: {
        size?: string;
        color?: string;
        price_min?: number;
        price_max?: number;
        sort?: "newest" | "price_asc" | "price_desc" | "popular";
        cursor?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Product list */
      200: {
        content: {
          "application/json": components["schemas"]["ProductList"];
        };
      };
    };
  };
  /** Get product by id or slug */
  getProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Product */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
    };
  };
  /** Get cart */
  getCart: {
    parameters: {
      header?: {
        "x-cart-id"?: string;
      };
    };
    responses: {
      /** @description Cart */
      200: {
        headers: {
          "x-cart-id"?: string;
        };
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
    };
  };
  /** Add item to cart */
  addCartItem: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddCartItem"];
      };
    };
    responses: {
      /** @description Cart */
      200: {
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
    };
  };
  /** Remove cart item */
  removeCartItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Removed */
      204: {
        content: never;
      };
    };
  };
  /** Update cart item */
  updateCartItem: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCartItem"];
      };
    };
    responses: {
      /** @description Cart */
      200: {
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
    };
  };
  /** Create checkout and compute totals */
  checkout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutRequest"];
      };
    };
    responses: {
      /** @description Checkout summary */
      200: {
        content: {
          "application/json": components["schemas"]["CheckoutSummary"];
        };
      };
    };
  };
  /** Initiate payment */
  createPayment: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaymentRequest"];
      };
    };
    responses: {
      /** @description Payment session */
      200: {
        content: {
          "application/json": components["schemas"]["PaymentSession"];
        };
      };
    };
  };
  /** SSLCommerz IPN callback */
  sslcommerzWebhook: {
    responses: {
      /** @description Accepted */
      204: {
        content: never;
      };
    };
  };
  /** ShurjoPay IPN callback */
  shurjopayWebhook: {
    responses: {
      /** @description Accepted */
      204: {
        content: never;
      };
    };
  };
  /** List orders for current user */
  listOrders: {
    responses: {
      /** @description Order list */
      200: {
        content: {
          "application/json": components["schemas"]["Order"][];
        };
      };
    };
  };
  /** Get order */
  getOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Order */
      200: {
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
    };
  };
}
